name: test

on:
  push:
    branches:
    tags:
  pull_request:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: install go
        uses: actions/setup-go@v1
        with:
          go-version: 1.22.1

      - name: test
        env:
          TBOT_SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          TBOT_SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        run: |
          go test -timeout=60s -covermode=count -coverprofile=$GITHUB_WORKSPACE/profile.cov_tmp ./...
          cat $GITHUB_WORKSPACE/profile.cov_tmp | grep -v "_mock.go" > $GITHUB_WORKSPACE/profile.cov
          go test -v -race ./...

      - name: install golangci-lint and goveralls
        run: |
          curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $GITHUB_WORKSPACE v1.20.0
          go install github.com/mattn/goveralls@latest

      - name: run linters
        run: |
          $GITHUB_WORKSPACE/golangci-lint run --out-format=tab --disable-all --tests=false --enable=unconvert \
            --enable=megacheck --enable=structcheck --enable=gocyclo --enable=dupl --enable=misspell \
            --enable=unparam --enable=varcheck --enable=deadcode --enable=typecheck \
            --enable=ineffassign ./... ;
    
      - name: submit coverage
        run: |
          $(go env GOPATH)/bin/goveralls -service="github" -coverprofile=$GITHUB_WORKSPACE/profile.cov
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}